# Generated by Django 6.0.4 on 2026-04-25 16:11

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
